CREATE TABLE user (
    `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
    `email`  VARCHAR(255) UNIQUE NOT NULL,
    `hash` VARCHAR(255) NOT NULL,
    `firstName` VARCHAR(255)  DEFAULT NULL,
    `lastName` VARCHAR(255) DEFAULT NULL,
    `dob` VARCHAR(255) DEFAULT NULL,
    `address` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`id`)
);